# Simple valid inputs for demo
tx_secret_key_r = "1"
amount_v = "1000000000000"
stealth_secret_H_s = "0x0000000000000000000000000000000000000000000000000000000000000001"

one_time_address_R_x = "0x0000000000000000000000000000000000000000000000000000000000000001"
one_time_address_R_y = "0x0000000000000000000000000000000000000000000000000000000000000001"
ecdh_encrypted_S_x = "0x0000000000000000000000000000000000000000000000000000000000000001"
ecdh_encrypted_S_y = "0x0000000000000000000000000000000000000000000000000000000000000001"
stealth_address_P_x = "0x0000000000000000000000000000000000000000000000000000000000000001"
stealth_address_P_y = "0x0000000000000000000000000000000000000000000000000000000000000001"
recipient_view_A_x = "0x0000000000000000000000000000000000000000000000000000000000000001"
recipient_view_A_y = "0x0000000000000000000000000000000000000000000000000000000000000001"
recipient_spend_B_x = "0x0000000000000000000000000000000000000000000000000000000000000001"
recipient_spend_B_y = "0x0000000000000000000000000000000000000000000000000000000000000001"
ecdh_amount = "1000000000000"
tx_hash = "0x0000000000000000000000000000000000000000000000000000000000000001"
output_index = "0"
commitment = "0x0000000000000000000000000000000000000000000000000000000000000001"
